bcgov/renovate-config

renovate.json
Dependency Dashboards have been a dud.  Teams aren't checking, so updates are sitting unapproved.  It's better to get those out the door.
=> Disable dependency dashboards

renovate.json
Disabling the dependency dashboard wasn't enough and major updates still aren't getting through automatically.  This PR should solve that.
=> feat: allow major updates through

.github/workflows/renovate.yml, renovate.json
Reduce the number of repos scanned in PRs.  This is always a dry-run, so no actual functionality is changed.
=> feat: limit PR dry runs to only two repos + action update

.github/workflows/renovate.yml
Prevent multiple workflow runs from the same source (PR, dispatch, cronjob).  Prevent running on merge to main, since nightly cronjobs are the expected plan.
Note: Renovate is a pretty large job.  Non-shortened configurations chew up a runner for over 10 minutes.
=> feat: add concurrency and stop running on main merge

.github/workflows/renovate.yml
Limit Renovate runs to just one repository using workflow_dispatch.
=> feat: workflow_dispatch single repo option

.github/workflows/renovate.yml
Debugging output would be too much for full-set jobs.  Instead debug when just one repo is targeted.
Idea thanks to @conbrad!  :)
=> feat: debug on individual runs

default.json
Reduce noise by grouping github-actions together.  Since the last rule wins on any conflicts this has been moved to the end.
Resolves https://github.com/bcgov/renovate-config/issues/112.
=> feat: batch more github-actions together

default.json
Thanks to @mhaswell-bcgov for the idea!  :)
=> chore(ci): include forks

default.json
All of our package manager types were set to use 3 stability days, except node, with 7.  This fixes that.
=> chore(ci): set node stability days to 3, like every other package manager

default.json
Default preset igmoreModulesAndTests has been excluding tests from receiving Renovate updates.  This blocks it.
=> chore(ci): do not exclude tests and modules

.github/workflows/renovate.yml, default.json, renovate.json
Run renovate-config-validator in primary workflow.  Plus simplifications.
=> chore(ci): renovate-config-validator in workflow

default.json
A few dependency updates, Java in particular, have hit before their prerequisites were ready.  Moving from 3 to 7 days seems like a reasonable idea.  We can fine tune this later, e.g. varying time for Java, TS/JS, Actions, etc.
=> chore: extend minimum release age to 7 days

rules-javascript.json5
Prevent prereleases from being pushed to our repositories.  JavaScript/TypeScript only.
=> fix: ignore prereleases

.github/workflows/renovate.yml, default.json, renovate.json
Exclude bcgov and actions (GitHub official) domains from pinning digests (SHAs).
=> chore(ci): exclude bcgov and actions domains from digest pinning

rules-actions.json5
Prevent pinning of postgres in GitHub Actions.  Here's an example where that isn't beneficial.
```
java:
name: Java
runs-on: ubuntu-24.04
services:
postgres:
image: postgres@sha256:864831322bf2520e7d03d899b01b542de6de9ece6fe29c89f19dc5e1d5568ccf
env:
POSTGRES_DB: postgres
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
options: >-
--health-cmd pg_isready
--health-interval 10s
--health-timeout 5s
--health-retries 5
ports:
- 5432:5432
steps:
...
```
=> chore: stop pinning official postgres in Actions workflows

default.json
Removed the enabled false flag as it does not appear to be respected
Attempts to enforce the original intent of the rule and fix #210 
Please delete options that are not relevant.
Verified on minimal reproduction repo here: https://github.com/jujaga/renovate-37124
=> fix(deps): Use Renovate regex negation syntax to exclude prereleases

default.json
**Summary:**  
This PR updates our global prerelease exclusion rule to avoid Terraform warnings.
**Details:**  
- Terraform does not support regex patterns for version constraints, which caused warnings when our global `matchCurrentVersion` regex was applied to Terraform dependencies.
- To resolve this, the rule now uses `matchManagers` to explicitly target only supported managers (e.g., npm, pip, docker, etc.), excluding Terraform and similar ecosystems.
- This preserves our established prerelease exclusion patterns for all relevant package managers, while preventing errors and warnings for Terraform.
**Note:**  
If we add new package managers in the future and want this exclusion to apply, we will need to update the `matchManagers` list accordingly.
=> fix: exclude terraform from regex rules

default.json
Batch Renovate activity before work hours to reduce daytime noise.
- timezone: America/Vancouver
- schedule: before 6am every weekday
- Predictable daily updates with less daytime churn.
=> chore(renovate-config): run Renovate before 6am every weekday

default.json
Teams were seeing '🚦 Automerge: Disabled because a matching PR was automerged previously' for DefinitelyTyped updates, preventing automatic merging of grouped @types/* package updates.
Added a specific automerge override rule for DefinitelyTyped packages while maintaining the grouping benefit.
- ✅ **Restored pre-release blocking rule** (security critical - was accidentally removed)
- ✅ **Kept group:definitelyTyped** for grouped PRs (less noise than individual PRs)
- ✅ **Added automerge override** for @types/* packages to force automerge
- ✅ **Validated configuration** with renovate-config-validator
- Configuration passes 
- Pre-release blocking rule restored to prevent alpha/beta/rc updates
- DefinitelyTyped packages will now automerge properly
This fix ensures teams get grouped …
=> fix: resolve DefinitelyTyped automerge disabled issue

.github/workflows/merge.yml
The release workflow was failing with 'GitHub Releases requires a tag' error because the conventional-changelog-action was configured to skip creating tags, but the action-gh-release was trying to reference a non-existent tag.
Added a new step 'Create Git Tag' that creates the actual Git tag before the release step, ensuring the tag exists when action-gh-release tries to create the GitHub release.
- Added 'Create Git Tag' step after conventional-changelog-action
- Configures git user for tag creation
- Creates and pushes the tag before release creation
This fixes the workflow error shown in the failed run.
=> fix: create git tag before release

default.json
**Problem:** Renovate is pinning service container digests (like postgres) in GitHub Actions workflows, which we want to prevent.
**Root Cause:** The global pinning rule was overriding the service container unpinning rule.
**Solution:** 
- Removed  from global pinning rule
- Added specific rule to pin GitHub Actions (excluding allowlisted orgs and service containers)
- Added separate rule for allowlisted orgs (actions/, docker/, github/)
- Service container rule now works correctly
**Impact:** This will stop Renovate from creating PRs that pin service container digests in GitHub Actions workflows.
**Example of the problem:** https://github.com/bcgov/quickstart-openshift/pull/2469
This needs to be merged quickly to prevent teams from merging unwanted pinning PRs.
=> fix: prevent service container pinning in GitHub Actions

.github/workflows/merge.yml
The previous workflow was completely broken due to tag creation conflicts, third-party action bugs, and limited version control. Tags would be created locally but fail to push, causing subsequent runs to fail.
Completely replaced the third-party `conventional-changelog-action` with our own robust implementation and added manual version override capability.
- **Replaced broken third-party action** with custom implementation
- **Fixed tag creation conflicts** with robust error handling
- **Added manual version override** for strategic releases
- **Comprehensive error handling** and recovery
- **Clean up existing local tags** to avoid conflicts
- **Push with fallback** to force update if needed
- **Check if tag exists remotely** and force update
- **Better error handling** and recovery
- …
=> feat: implement custom release workflow with manual version override

default.json
Add branch protection rule to prevent teams from getting unexpected version format changes. This ensures teams stay at their chosen decimal precision level.
- Add `allowedVersions` regex rule for `bcgov/renovate-config`
- Prevent decimal precision changes (e.g., v1.0.0 → v1.2)
- Allow same-precision updates (e.g., v1.0.0 → v1.0.1, v1.1.0, v2.0.0)
- Block precision changes that could break team expectations
The `quickstart-openshift` repository was getting PRs to upgrade from `v1.0.0` to `v1.2`, which changes from 3 decimals to 2 decimals. This violates the principle that teams should stay at their chosen version precision level.
- **Rule**: `allowedVersions: "/^v?\\d+\\.\\d+\\.\\d+$/"` for 3-decimal versions
- **Effect**: Teams using `v1.0.0` only get 3-decimal updates
- **Prevents**: …
=> fix: prevent decimal precision changes for renovate-config

default.json
Some downstream repositories are getting service container pinning PRs despite our infrastructure unpinning rules:
- Service containers (like postgres, redis) are detected as 'service' type
- Our unpinning rules only covered dockerfile, docker-compose, kubernetes managers
- Service containers should use stable tags, not digests
Add unpinning rule for service containers:
- New rule: unpin all 'service' type containers
- This covers postgres, redis, and other service containers
- Service containers should use stable tags, not digests
- Validation script passes with no conflicts
- Integration test passes
- No pinning conflicts detected
- default.json - Added service container unpinning rule
This should fix service container pinning issues across all downstream repositories.
=> fix: add service container unpinning rule

.github/workflows/merge.yml
The release workflow was maintaining changelog files, which is an antipattern. GitHub releases already provide changelog information automatically.
* Removed changelog generation entirely
* Simplified workflow to focus on versioning and tagging only
* Eliminated maintenance overhead of changelog files
* Reduced workflow complexity and potential failure points
* ✅ **No maintenance overhead** - GitHub releases handle changelog automatically
* ✅ **Simplified workflow** - fewer steps, fewer failure points
* ✅ **Best practices** - no redundant changelog file antipattern
* ✅ **Consistent information** - single source of truth in GitHub releases
This change simplifies the release workflow while maintaining all versioning functionality. Users can find changelog information in the GitHub releases …
=> refactor: simplify release workflow by removing changelog generation

.github/workflows/merge.yml
This PR fixes the release workflow to preserve individual patch version tags (e.g., v1.0.0) while still updating major (v1) and minor (v1.0) tags to point to the latest release. It also adds proper error handling for git tag operations.
*   **Release Workflow Fix**: Modified  to ensure  and  are used, preserving all existing patch tags.
*   **Error Handling**: Added proper error handling for git tag operations to check if tag creation succeeds before attempting to push.
*   **Preserves Version History**: Individual patch version tags (e.g., v1.0.0) are no longer lost when new releases are made, allowing teams to pin to exact versions.
*   **Better Error Handling**: Git tag operations now properly check for success before proceeding to push operations.
*   **Clearer Output**: Improved …
=> fix: preserve patch tags in release workflow and add error handling

rules-actions.json5
This PR fixes the preset loading issue by simplifying the regex patterns in matchPackageNames while keeping the file as JSON5 format.
The complex regex patterns like  were causing parsing issues. Simplified to  which should work for the intended use case.
Fixes: https://github.com/bcgov/quickstart-aws-sql/issues/169
=> fix: simplify regex patterns in rules-actions.json5

.copilot-instructions.md, default.json, renovate.json
This PR adds a package rule to automatically send PRs to downstream repositories that are using the unversioned `github>bcgov/renovate-config` reference, encouraging them to upgrade to the stable `github>bcgov/renovate-config#v1` tag.
- **Targets**: Repositories using `github>bcgov/renovate-config` (unversioned)
- **Updates to**: `github>bcgov/renovate-config#v1`
- **Ignores**: Repositories already using specific version tags (e.g., `#v1.0.0`, `#v1.0`)
- Uses `matchCurrentVersion: "/^v\\d+\\.\\d+(\\.\\d+)?$/"` to exclude versioned references
- Sets `allowedVersions: "v1"` to only allow updates to the v1 tag
- Includes `recreateWhen: "never"` to ensure one-time PR creation
- Provides clear PR messaging about benefits and changes
- ✅ **Stable updates** - get tested releases, not development …
=> feat: add package rule to update unversioned renovate-config references to v1

default.json
This PR addresses critical issues that were preventing teams from receiving the v1.0.0 update PRs and improves overall config stability and reliability.
Teams using the unversioned `github>bcgov/renovate-config` reference were not receiving PRs to upgrade to v1.0.0. Investigation revealed several issues:
- **Issue**: Rules used mixed package names (`"bcgov/renovate-config"` vs `"github>bcgov/renovate-config"`)
- **Impact**: Rules couldn't match properly, preventing PR creation
- **Fix**: Standardized all rules to use `"github>bcgov/renovate-config"`
- **Issue**: Only targeted `"renovate.json"` files
- **Impact**: Missed configs in `.github/renovate.json` or `renovate.json5`
- **Fix**: Added support for multiple config file locations
- **Issue**: No error handling or stability settings
- …
=> fix: package name consistency and config improvements

default.json
This PR simplifies the prerelease blocking rule by removing the explicit manager list, making it more maintainable and future-proof.
The prerelease blocking rule had an explicit list of all package managers:
- **Maintenance burden**: Need to update list when new managers are added
- **Error-prone**: Easy to miss a manager
- **Redundant**: Lists every single manager explicitly
Removed the explicit  list, letting the rule apply to all managers automatically:
- ✅ **Simpler**: No explicit manager list to maintain
- ✅ **Future-proof**: Automatically applies to new managers
- ✅ **Less error-prone**: No risk of missing managers
- ✅ **Same functionality**: Still blocks prereleases globally
- ✅ **Validates successfully**: Configuration passes all checks
- ✅ **Configuration validates successfully** …
=> refactor: simplify prerelease blocking rule

default.json
This PR fixes the  configuration by adding the required  capture group to the regex pattern.
- Added  capture group to the  regex
- This allows Renovate to properly identify and replace unversioned references
The  feature requires a  capture group in the regex to work properly. Without it, Renovate cannot identify what needs to be replaced.
Downstream repositories using unversioned  references should now receive PRs to update to .
This is the simplest possible fix using the official Renovate  approach.
=> fix: add currentValue capture group to customManagers regex

default.json
The  configuration was using  which contains a `>` character. This caused Git branch name creation to fail because it is not a valid character in branch names.
Changed to use a valid branch name format.
- Configuration validates successfully
- Should now properly create branches and PRs for repositories using unversioned  references
This fixes the issue where downstream repositories were not receiving PRs due to invalid branch name creation.
=> fix: use valid branch name for customManagers depNameTemplate

default.json
Changed the datasource for the regex manager from  to :
- Renovate was skipping the unversioned reference with 
- The  datasource doesn't handle unversioned references like  properly
- Changed  from  to 
-  datasource should better handle unversioned references
- The debug logs showed our regex manager is working correctly
- It's detecting the dependency and current value properly
- The issue appears to be datasource validation, not regex pattern matching
-  is more appropriate for repository references that don't specify versions
This should resolve the  issue and allow the v1 migration to proceed.
=> fix: change datasource to github-tags for unversioned references

default.json
This PR adapts the proven working Yarn regex manager pattern to handle the migration of unversioned renovate-config references to v1.
- Use capture group  pattern from working examples instead of 
- Adapt the exact structure used in the Yarn example: , , , 
- Target unversioned  references
- Replace with  using templating variables
The configuration follows the exact pattern from the working Yarn example:
- **Capture group extraction**: 
- **Template-based replacement**: 
- **Required datasource**:  (for tag-based references)
This approach is more reliable than previous attempts as it follows proven working patterns rather than experimental configurations.
=> fix: adapt working regex manager pattern for renovate-config migration

README.md, default.json
Removes container unpinning rules that only prevented new SHA pins but didn't remove existing ones. Since prevention is working well, this simplifies the configuration without changing effective behavior.
=> chore: remove ineffective container unpinning rules

default.json, rules-infrastructure.json5, rules-java.json5, rules-javascript.json5, rules-python.json5
The current structure was inconsistent - we had ecosystem-specific grouping rules in  mixed with global policies, while the  files were intended for ecosystem-specific rules.
Move ecosystem-specific grouping rules from  to their appropriate  files:
- **Infrastructure rules** → new 
- **Node.js ecosystem rules** →   
- **Java ecosystem rules** → 
- **Python ecosystem rules** → 
** now contains only:**
- Global pinning policy (applies to multiple ecosystems)
- Config preset prevention (meta-rule about the config itself)  
- Prerelease blocking (global policy)
** files contain:**
- Ecosystem-specific grouping rules
- Framework-specific rules (vite, angular, etc.)
✅ **Consistent structure** - ecosystem rules live in ecosystem files  
✅ **Easier maintenance** - find Node rules in   
✅ …
=> refactor: reorganize ecosystem rules for consistency

default.json, rules-actions.json5, rules-java.json5, rules-javascript.json5, rules-python.json5
Comprehensive cleanup and reorganization of Renovate configuration to improve maintainability and reduce redundancy.
- **Moved global pinning rule** from `default.json` to ecosystem-specific files:
- `rules-java.json5`: Pin Java digests for `gradle`, `maven`
- `rules-javascript.json5`: Pin JavaScript digests for `npm`, `pnpm`, `yarn`
- `rules-python.json5`: Pin Python digests for `pip`, `pipenv`, `poetry`, `uv`
- **Better organization**: Pinning policies now live with their respective ecosystems
- **Removed "Prevent config preset pinning" rule** from `default.json`
- **Reason**: Became redundant after moving to ecosystem-specific pinning
- **Impact**: Cleaner configuration without functional changes
- **Removed unused `customManagers`** for v1 migration regex
- **Removed unused …
=> refactor: move pinning rules to ecosystem files and cleanup config

default.json
This PR tests the packageRule-based migration approach found in commit 1e4d350 from the bk-main branch.
- **Targets**: Repositories using unversioned  references
- **Updates**: Changes them to 
- **Excludes**: Repositories already using versioned references (v1, v1.0, v1.0.0, etc.)
- ✅ **Uses packageRule** instead of customManagers (more reliable)
- ✅ **Targets specific package** 
- ✅ **Uses negative regex** to exclude versioned references
- ✅ **Sets allowedVersions** to v1 (forces the target version)
1. **Point test repo** to this branch: 
2. **Use unversioned config** in test repo: 
3. **Run Renovate** and see if migration works with fresh cache
4. **If successful** → merge to main and update tags
5. **If unsuccessful** → FINALLY give up on migration
This is our last attempt. Previous …
=> feat: attempted unversioned to v1 migration

.github/workflows/renovate.yml, lint_renovate_duplicates.mjs
This PR includes two important improvements:
- Updated example output comments to reference `rules-infra.json5` instead of `rules-actions.json5`
- Fixed hardcoded filename references in documentation comments
- Maintains consistency with actual file names
- **Problem**: Dry-run workflow was showing success even when Renovate found configuration errors
- **Solution**: Added Validate Configuration step that:
- Runs Renovate directly with Docker to capture all output
- Searches for `validationError`, `config-validation`, and `Cannot find preset` errors
- **Fails the workflow** (exit code 1) when configuration errors are detected
- Provides clear error reporting and success confirmation
- ✅ Ensures documentation accuracy in lint script
- ✅ Prevents confusion about file names
- ✅ **Critical …
=> fix: update lint script references and improve dry-run validation
