- .github/dependabot.yml
- .github/workflows/renovate.yml
> Disable Dependabot dependency updates

- .github/workflows/renovate.yml
Make sure PRs only do a dry run.
> feat: force dry run on PRs

- renovate.json
Just including old growth to the party
> feat: adding old growth to renovate list

- .github/workflows/renovate.yml
Correction to PR dry run always being applied.
> bug: dry run not correctly applied

- .github/CODEOWNERS
Codeowners file.  Makes sure all are notified and that at least one of us approves.
> .github/CODEOWNERS

- renovate.json
- @angular/*
- @angular-devkit/*
- @angular-eslint/*
> Group angular co-requisites

- renovate.json
Grouping for boto3 and botocore.
> Feat: group boto3 and botocore (python)

- renovate.json
Python dependency groups:
- pytest
- sqlalchemy
Plus cleanup.
> Python groups, cleanup

- .github/workflows/renovate.yml
Causing specfic-repo runs to update incorrectly, running for everything.
> bug: fix checkout location in workflow

- renovate.json
> feat: add repo

- renovate.json
Requires automerge to be enabled for individual repos.
> feat: automerge for digests, minor, patch, lockfile

- default.json
> chore: JS group aws-amplify

- default.json
> fix: mui group name

- default.json
Duplicated setting.  One disabled, one enabled.  Whoops.
> fix(ci): conflicting fork handling

- default.json
Changes are only picked up from the main/default branch, so we're stuck merging and watching, which stinks.
> fix: split preset formatting

- .github/workflows/renovate.yml
Workflow permissions alert.
https://github.com/bcgov/renovate-config/security/code-scanning/1
> chore(ci): workflow permissions

- .github/workflows/renovate.yml
- default.json
- rules-javascript.json5
- rules-python.json5
> chore: migrate config

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- default.json
- renovate.json
- rules-actions.json5
- rules-java.json5
- rules-javascript.json5
- rules-python.json5
Lots of assistance from Copilot agent mode.
> chore: readme, comments and cleanup

- rules-containers.json5
Previous attempt unsuccessful.
> chore(ci): keep trying to block pins for containers in workflows

- .github/workflows/renovate.yml
- README.md
- default.json
- lint_renovate_duplicates.mjs
Reverts bcgov/renovate-config#215
Caused dependency dashboards to close. Ungrouped PRs.
> chore: Revert "chore(ci): switch default config to JSON5, add comments"

- .github/workflows/renovate.yml
- scripts/validate-renovate.sh
- **Added validation for invalid commitMessageAction values** - catches 'upgrade' (should be 'replace', 'append', or 'prepend')
- **Added validation for contradictory enabled: true with blocking properties** - catches the issue Copilot flagged
- **Added validation for invalid allowedVersions regex patterns** - validates regex syntax
- **Updated workflow to use enhanced bash script** - removed duplicate Node.js script
These checks will catch the exact issues we just fixed:
- Invalid commitMessageAction values like 'upgrade' instead of 'replace'
- enabled: true with blocking properties (should be enabled: false for blocking)
- Invalid regex patterns in allowedVersions
The enhanced validation script now catches configuration errors before they reach GitHub, saving API calls and preventing …
> feat: enhance validation script with Copilot-caught checks
